// Code generated by go-swagger;

package management_rest_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetFileSystemInfoParams creates a new GetFileSystemInfoParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetFileSystemInfoParams() *GetFileSystemInfoParams {
	return &GetFileSystemInfoParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetFileSystemInfoParamsWithTimeout creates a new GetFileSystemInfoParams object
// with the ability to set a timeout on a request.
func NewGetFileSystemInfoParamsWithTimeout(timeout time.Duration) *GetFileSystemInfoParams {
	return &GetFileSystemInfoParams{
		timeout: timeout,
	}
}

// NewGetFileSystemInfoParamsWithContext creates a new GetFileSystemInfoParams object
// with the ability to set a context for a request.
func NewGetFileSystemInfoParamsWithContext(ctx context.Context) *GetFileSystemInfoParams {
	return &GetFileSystemInfoParams{
		Context: ctx,
	}
}

// NewGetFileSystemInfoParamsWithHTTPClient creates a new GetFileSystemInfoParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetFileSystemInfoParamsWithHTTPClient(client *http.Client) *GetFileSystemInfoParams {
	return &GetFileSystemInfoParams{
		HTTPClient: client,
	}
}

/* GetFileSystemInfoParams contains all the parameters to send to the API endpoint
   for the get file system info operation.

   Typically these are written to a http.Request.
*/
type GetFileSystemInfoParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get file system info params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetFileSystemInfoParams) WithDefaults() *GetFileSystemInfoParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get file system info params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetFileSystemInfoParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get file system info params
func (o *GetFileSystemInfoParams) WithTimeout(timeout time.Duration) *GetFileSystemInfoParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get file system info params
func (o *GetFileSystemInfoParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get file system info params
func (o *GetFileSystemInfoParams) WithContext(ctx context.Context) *GetFileSystemInfoParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get file system info params
func (o *GetFileSystemInfoParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get file system info params
func (o *GetFileSystemInfoParams) WithHTTPClient(client *http.Client) *GetFileSystemInfoParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get file system info params
func (o *GetFileSystemInfoParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetFileSystemInfoParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
