// Code generated by go-swagger; DO NOT EDIT.

package management_rest_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetUserListParams creates a new GetUserListParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetUserListParams() *GetUserListParams {
	return &GetUserListParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetUserListParamsWithTimeout creates a new GetUserListParams object
// with the ability to set a timeout on a request.
func NewGetUserListParamsWithTimeout(timeout time.Duration) *GetUserListParams {
	return &GetUserListParams{
		timeout: timeout,
	}
}

// NewGetUserListParamsWithContext creates a new GetUserListParams object
// with the ability to set a context for a request.
func NewGetUserListParamsWithContext(ctx context.Context) *GetUserListParams {
	return &GetUserListParams{
		Context: ctx,
	}
}

// NewGetUserListParamsWithHTTPClient creates a new GetUserListParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetUserListParamsWithHTTPClient(client *http.Client) *GetUserListParams {
	return &GetUserListParams{
		HTTPClient: client,
	}
}

/* GetUserListParams contains all the parameters to send to the API endpoint
   for the get user list operation.

   Typically these are written to a http.Request.
*/
type GetUserListParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get user list params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetUserListParams) WithDefaults() *GetUserListParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get user list params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetUserListParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get user list params
func (o *GetUserListParams) WithTimeout(timeout time.Duration) *GetUserListParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get user list params
func (o *GetUserListParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get user list params
func (o *GetUserListParams) WithContext(ctx context.Context) *GetUserListParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get user list params
func (o *GetUserListParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get user list params
func (o *GetUserListParams) WithHTTPClient(client *http.Client) *GetUserListParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get user list params
func (o *GetUserListParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetUserListParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
