// Code generated by go-swagger; DO NOT EDIT.

package management_rest_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"antmedia/models"
)

// GetServerSettingsReader is a Reader for the GetServerSettings structure.
type GetServerSettingsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetServerSettingsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetServerSettingsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetServerSettingsOK creates a GetServerSettingsOK with default headers values
func NewGetServerSettingsOK() *GetServerSettingsOK {
	return &GetServerSettingsOK{}
}

/* GetServerSettingsOK describes a response with status code 200, with default header values.

successful operation
*/
type GetServerSettingsOK struct {
	Payload *models.Result
}

func (o *GetServerSettingsOK) Error() string {
	return fmt.Sprintf("[GET /v2/server-settings][%d] getServerSettingsOK  %+v", 200, o.Payload)
}
func (o *GetServerSettingsOK) GetPayload() *models.Result {
	return o.Payload
}

func (o *GetServerSettingsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Result)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
