// Code generated by go-swagger; DO NOT EDIT.

package management_rest_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetGPUInfoParams creates a new GetGPUInfoParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetGPUInfoParams() *GetGPUInfoParams {
	return &GetGPUInfoParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetGPUInfoParamsWithTimeout creates a new GetGPUInfoParams object
// with the ability to set a timeout on a request.
func NewGetGPUInfoParamsWithTimeout(timeout time.Duration) *GetGPUInfoParams {
	return &GetGPUInfoParams{
		timeout: timeout,
	}
}

// NewGetGPUInfoParamsWithContext creates a new GetGPUInfoParams object
// with the ability to set a context for a request.
func NewGetGPUInfoParamsWithContext(ctx context.Context) *GetGPUInfoParams {
	return &GetGPUInfoParams{
		Context: ctx,
	}
}

// NewGetGPUInfoParamsWithHTTPClient creates a new GetGPUInfoParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetGPUInfoParamsWithHTTPClient(client *http.Client) *GetGPUInfoParams {
	return &GetGPUInfoParams{
		HTTPClient: client,
	}
}

/* GetGPUInfoParams contains all the parameters to send to the API endpoint
   for the get g p u info operation.

   Typically these are written to a http.Request.
*/
type GetGPUInfoParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get g p u info params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetGPUInfoParams) WithDefaults() *GetGPUInfoParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get g p u info params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetGPUInfoParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get g p u info params
func (o *GetGPUInfoParams) WithTimeout(timeout time.Duration) *GetGPUInfoParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get g p u info params
func (o *GetGPUInfoParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get g p u info params
func (o *GetGPUInfoParams) WithContext(ctx context.Context) *GetGPUInfoParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get g p u info params
func (o *GetGPUInfoParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get g p u info params
func (o *GetGPUInfoParams) WithHTTPClient(client *http.Client) *GetGPUInfoParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get g p u info params
func (o *GetGPUInfoParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetGPUInfoParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
