// Code generated by go-swagger;

package management_rest_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"antmedia/models"
)

// IsShutdownProperlyReader is a Reader for the IsShutdownProperly structure.
type IsShutdownProperlyReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *IsShutdownProperlyReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewIsShutdownProperlyOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewIsShutdownProperlyBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewIsShutdownProperlyOK creates a IsShutdownProperlyOK with default headers values
func NewIsShutdownProperlyOK() *IsShutdownProperlyOK {
	return &IsShutdownProperlyOK{}
}

/* IsShutdownProperlyOK describes a response with status code 200, with default header values.

Returns the shutdown status of entered applications.
*/
type IsShutdownProperlyOK struct {
	Payload *models.Result
}

func (o *IsShutdownProperlyOK) Error() string {
	return fmt.Sprintf("[GET /v2/shutdown-proper-status][%d] isShutdownProperlyOK  %+v", 200, o.Payload)
}
func (o *IsShutdownProperlyOK) GetPayload() *models.Result {
	return o.Payload
}

func (o *IsShutdownProperlyOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Result)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewIsShutdownProperlyBadRequest creates a IsShutdownProperlyBadRequest with default headers values
func NewIsShutdownProperlyBadRequest() *IsShutdownProperlyBadRequest {
	return &IsShutdownProperlyBadRequest{}
}

/* IsShutdownProperlyBadRequest describes a response with status code 400, with default header values.

Either entered in wrong format or typed incorrectly application names
*/
type IsShutdownProperlyBadRequest struct {
}

func (o *IsShutdownProperlyBadRequest) Error() string {
	return fmt.Sprintf("[GET /v2/shutdown-proper-status][%d] isShutdownProperlyBadRequest ", 400)
}

func (o *IsShutdownProperlyBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
