// Code generated by go-swagger;

package broadcast_rest_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/umutbasal/antmedia/models"
)

// AddSubTrackReader is a Reader for the AddSubTrack structure.
type AddSubTrackReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AddSubTrackReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewAddSubTrackOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewAddSubTrackOK creates a AddSubTrackOK with default headers values
func NewAddSubTrackOK() *AddSubTrackOK {
	return &AddSubTrackOK{}
}

/* AddSubTrackOK describes a response with status code 200, with default header values.

successful operation
*/
type AddSubTrackOK struct {
	Payload *models.Result
}

func (o *AddSubTrackOK) Error() string {
	return fmt.Sprintf("[POST /v2/broadcasts/{id}/subtrack][%d] addSubTrackOK  %+v", 200, o.Payload)
}
func (o *AddSubTrackOK) GetPayload() *models.Result {
	return o.Payload
}

func (o *AddSubTrackOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Result)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
