// Code generated by go-swagger;

package broadcast_rest_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteConferenceRoomV2Params creates a new DeleteConferenceRoomV2Params object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteConferenceRoomV2Params() *DeleteConferenceRoomV2Params {
	return &DeleteConferenceRoomV2Params{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteConferenceRoomV2ParamsWithTimeout creates a new DeleteConferenceRoomV2Params object
// with the ability to set a timeout on a request.
func NewDeleteConferenceRoomV2ParamsWithTimeout(timeout time.Duration) *DeleteConferenceRoomV2Params {
	return &DeleteConferenceRoomV2Params{
		timeout: timeout,
	}
}

// NewDeleteConferenceRoomV2ParamsWithContext creates a new DeleteConferenceRoomV2Params object
// with the ability to set a context for a request.
func NewDeleteConferenceRoomV2ParamsWithContext(ctx context.Context) *DeleteConferenceRoomV2Params {
	return &DeleteConferenceRoomV2Params{
		Context: ctx,
	}
}

// NewDeleteConferenceRoomV2ParamsWithHTTPClient creates a new DeleteConferenceRoomV2Params object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteConferenceRoomV2ParamsWithHTTPClient(client *http.Client) *DeleteConferenceRoomV2Params {
	return &DeleteConferenceRoomV2Params{
		HTTPClient: client,
	}
}

/* DeleteConferenceRoomV2Params contains all the parameters to send to the API endpoint
   for the delete conference room v2 operation.

   Typically these are written to a http.Request.
*/
type DeleteConferenceRoomV2Params struct {

	/* RoomID.

	   the id of the conference room
	*/
	RoomID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete conference room v2 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteConferenceRoomV2Params) WithDefaults() *DeleteConferenceRoomV2Params {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete conference room v2 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteConferenceRoomV2Params) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete conference room v2 params
func (o *DeleteConferenceRoomV2Params) WithTimeout(timeout time.Duration) *DeleteConferenceRoomV2Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete conference room v2 params
func (o *DeleteConferenceRoomV2Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete conference room v2 params
func (o *DeleteConferenceRoomV2Params) WithContext(ctx context.Context) *DeleteConferenceRoomV2Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete conference room v2 params
func (o *DeleteConferenceRoomV2Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete conference room v2 params
func (o *DeleteConferenceRoomV2Params) WithHTTPClient(client *http.Client) *DeleteConferenceRoomV2Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete conference room v2 params
func (o *DeleteConferenceRoomV2Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRoomID adds the roomID to the delete conference room v2 params
func (o *DeleteConferenceRoomV2Params) WithRoomID(roomID string) *DeleteConferenceRoomV2Params {
	o.SetRoomID(roomID)
	return o
}

// SetRoomID adds the roomId to the delete conference room v2 params
func (o *DeleteConferenceRoomV2Params) SetRoomID(roomID string) {
	o.RoomID = roomID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteConferenceRoomV2Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param room_id
	if err := r.SetPathParam("room_id", o.RoomID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
