// Code generated by go-swagger;

package broadcast_rest_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/umutbasal/antmedia/models"
)

// GetBroadcastStatisticsReader is a Reader for the GetBroadcastStatistics structure.
type GetBroadcastStatisticsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetBroadcastStatisticsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetBroadcastStatisticsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetBroadcastStatisticsOK creates a GetBroadcastStatisticsOK with default headers values
func NewGetBroadcastStatisticsOK() *GetBroadcastStatisticsOK {
	return &GetBroadcastStatisticsOK{}
}

/* GetBroadcastStatisticsOK describes a response with status code 200, with default header values.

successful operation
*/
type GetBroadcastStatisticsOK struct {
	Payload *models.BroadcastStatistics
}

func (o *GetBroadcastStatisticsOK) Error() string {
	return fmt.Sprintf("[GET /v2/broadcasts/{id}/broadcast-statistics][%d] getBroadcastStatisticsOK  %+v", 200, o.Payload)
}
func (o *GetBroadcastStatisticsOK) GetPayload() *models.BroadcastStatistics {
	return o.Payload
}

func (o *GetBroadcastStatisticsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.BroadcastStatistics)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
