// Code generated by go-swagger; DO NOT EDIT.

package broadcast_rest_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetRTMPToWebRTCStatsParams creates a new GetRTMPToWebRTCStatsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetRTMPToWebRTCStatsParams() *GetRTMPToWebRTCStatsParams {
	return &GetRTMPToWebRTCStatsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetRTMPToWebRTCStatsParamsWithTimeout creates a new GetRTMPToWebRTCStatsParams object
// with the ability to set a timeout on a request.
func NewGetRTMPToWebRTCStatsParamsWithTimeout(timeout time.Duration) *GetRTMPToWebRTCStatsParams {
	return &GetRTMPToWebRTCStatsParams{
		timeout: timeout,
	}
}

// NewGetRTMPToWebRTCStatsParamsWithContext creates a new GetRTMPToWebRTCStatsParams object
// with the ability to set a context for a request.
func NewGetRTMPToWebRTCStatsParamsWithContext(ctx context.Context) *GetRTMPToWebRTCStatsParams {
	return &GetRTMPToWebRTCStatsParams{
		Context: ctx,
	}
}

// NewGetRTMPToWebRTCStatsParamsWithHTTPClient creates a new GetRTMPToWebRTCStatsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetRTMPToWebRTCStatsParamsWithHTTPClient(client *http.Client) *GetRTMPToWebRTCStatsParams {
	return &GetRTMPToWebRTCStatsParams{
		HTTPClient: client,
	}
}

/* GetRTMPToWebRTCStatsParams contains all the parameters to send to the API endpoint
   for the get r t m p to web r t c stats operation.

   Typically these are written to a http.Request.
*/
type GetRTMPToWebRTCStatsParams struct {

	/* ID.

	   the id of the stream
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get r t m p to web r t c stats params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetRTMPToWebRTCStatsParams) WithDefaults() *GetRTMPToWebRTCStatsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get r t m p to web r t c stats params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetRTMPToWebRTCStatsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get r t m p to web r t c stats params
func (o *GetRTMPToWebRTCStatsParams) WithTimeout(timeout time.Duration) *GetRTMPToWebRTCStatsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get r t m p to web r t c stats params
func (o *GetRTMPToWebRTCStatsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get r t m p to web r t c stats params
func (o *GetRTMPToWebRTCStatsParams) WithContext(ctx context.Context) *GetRTMPToWebRTCStatsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get r t m p to web r t c stats params
func (o *GetRTMPToWebRTCStatsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get r t m p to web r t c stats params
func (o *GetRTMPToWebRTCStatsParams) WithHTTPClient(client *http.Client) *GetRTMPToWebRTCStatsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get r t m p to web r t c stats params
func (o *GetRTMPToWebRTCStatsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get r t m p to web r t c stats params
func (o *GetRTMPToWebRTCStatsParams) WithID(id string) *GetRTMPToWebRTCStatsParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get r t m p to web r t c stats params
func (o *GetRTMPToWebRTCStatsParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetRTMPToWebRTCStatsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
