// Code generated by go-swagger; DO NOT EDIT.

package broadcast_rest_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetWebRTCViewerListParams creates a new GetWebRTCViewerListParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetWebRTCViewerListParams() *GetWebRTCViewerListParams {
	return &GetWebRTCViewerListParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetWebRTCViewerListParamsWithTimeout creates a new GetWebRTCViewerListParams object
// with the ability to set a timeout on a request.
func NewGetWebRTCViewerListParamsWithTimeout(timeout time.Duration) *GetWebRTCViewerListParams {
	return &GetWebRTCViewerListParams{
		timeout: timeout,
	}
}

// NewGetWebRTCViewerListParamsWithContext creates a new GetWebRTCViewerListParams object
// with the ability to set a context for a request.
func NewGetWebRTCViewerListParamsWithContext(ctx context.Context) *GetWebRTCViewerListParams {
	return &GetWebRTCViewerListParams{
		Context: ctx,
	}
}

// NewGetWebRTCViewerListParamsWithHTTPClient creates a new GetWebRTCViewerListParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetWebRTCViewerListParamsWithHTTPClient(client *http.Client) *GetWebRTCViewerListParams {
	return &GetWebRTCViewerListParams{
		HTTPClient: client,
	}
}

/* GetWebRTCViewerListParams contains all the parameters to send to the API endpoint
   for the get web r t c viewer list operation.

   Typically these are written to a http.Request.
*/
type GetWebRTCViewerListParams struct {

	/* Offset.

	   This is the offset of the list, it is useful for pagination. If you want to use sort mechanism, we recommend using Mongo DB.

	   Format: int32
	*/
	Offset int32

	/* OrderBy.

	   asc for Ascending, desc Descending order
	*/
	OrderBy *string

	/* Search.

	   Search parameter, returns specific items that contains search string
	*/
	Search *string

	/* Size.

	   Number of items that will be fetched. If there is not enough item in the datastore, returned list size may less then this value

	   Format: int32
	*/
	Size int32

	/* SortBy.

	   field to sort
	*/
	SortBy *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get web r t c viewer list params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetWebRTCViewerListParams) WithDefaults() *GetWebRTCViewerListParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get web r t c viewer list params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetWebRTCViewerListParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get web r t c viewer list params
func (o *GetWebRTCViewerListParams) WithTimeout(timeout time.Duration) *GetWebRTCViewerListParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get web r t c viewer list params
func (o *GetWebRTCViewerListParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get web r t c viewer list params
func (o *GetWebRTCViewerListParams) WithContext(ctx context.Context) *GetWebRTCViewerListParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get web r t c viewer list params
func (o *GetWebRTCViewerListParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get web r t c viewer list params
func (o *GetWebRTCViewerListParams) WithHTTPClient(client *http.Client) *GetWebRTCViewerListParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get web r t c viewer list params
func (o *GetWebRTCViewerListParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOffset adds the offset to the get web r t c viewer list params
func (o *GetWebRTCViewerListParams) WithOffset(offset int32) *GetWebRTCViewerListParams {
	o.SetOffset(offset)
	return o
}

// SetOffset adds the offset to the get web r t c viewer list params
func (o *GetWebRTCViewerListParams) SetOffset(offset int32) {
	o.Offset = offset
}

// WithOrderBy adds the orderBy to the get web r t c viewer list params
func (o *GetWebRTCViewerListParams) WithOrderBy(orderBy *string) *GetWebRTCViewerListParams {
	o.SetOrderBy(orderBy)
	return o
}

// SetOrderBy adds the orderBy to the get web r t c viewer list params
func (o *GetWebRTCViewerListParams) SetOrderBy(orderBy *string) {
	o.OrderBy = orderBy
}

// WithSearch adds the search to the get web r t c viewer list params
func (o *GetWebRTCViewerListParams) WithSearch(search *string) *GetWebRTCViewerListParams {
	o.SetSearch(search)
	return o
}

// SetSearch adds the search to the get web r t c viewer list params
func (o *GetWebRTCViewerListParams) SetSearch(search *string) {
	o.Search = search
}

// WithSize adds the size to the get web r t c viewer list params
func (o *GetWebRTCViewerListParams) WithSize(size int32) *GetWebRTCViewerListParams {
	o.SetSize(size)
	return o
}

// SetSize adds the size to the get web r t c viewer list params
func (o *GetWebRTCViewerListParams) SetSize(size int32) {
	o.Size = size
}

// WithSortBy adds the sortBy to the get web r t c viewer list params
func (o *GetWebRTCViewerListParams) WithSortBy(sortBy *string) *GetWebRTCViewerListParams {
	o.SetSortBy(sortBy)
	return o
}

// SetSortBy adds the sortBy to the get web r t c viewer list params
func (o *GetWebRTCViewerListParams) SetSortBy(sortBy *string) {
	o.SortBy = sortBy
}

// WriteToRequest writes these params to a swagger request
func (o *GetWebRTCViewerListParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param offset
	if err := r.SetPathParam("offset", swag.FormatInt32(o.Offset)); err != nil {
		return err
	}

	if o.OrderBy != nil {

		// query param order_by
		var qrOrderBy string

		if o.OrderBy != nil {
			qrOrderBy = *o.OrderBy
		}
		qOrderBy := qrOrderBy
		if qOrderBy != "" {

			if err := r.SetQueryParam("order_by", qOrderBy); err != nil {
				return err
			}
		}
	}

	if o.Search != nil {

		// query param search
		var qrSearch string

		if o.Search != nil {
			qrSearch = *o.Search
		}
		qSearch := qrSearch
		if qSearch != "" {

			if err := r.SetQueryParam("search", qSearch); err != nil {
				return err
			}
		}
	}

	// path param size
	if err := r.SetPathParam("size", swag.FormatInt32(o.Size)); err != nil {
		return err
	}

	if o.SortBy != nil {

		// query param sort_by
		var qrSortBy string

		if o.SortBy != nil {
			qrSortBy = *o.SortBy
		}
		qSortBy := qrSortBy
		if qSortBy != "" {

			if err := r.SetQueryParam("sort_by", qSortBy); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
