// Code generated by go-swagger;

package broadcast_rest_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetCameraErrorV2Params creates a new GetCameraErrorV2Params object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetCameraErrorV2Params() *GetCameraErrorV2Params {
	return &GetCameraErrorV2Params{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetCameraErrorV2ParamsWithTimeout creates a new GetCameraErrorV2Params object
// with the ability to set a timeout on a request.
func NewGetCameraErrorV2ParamsWithTimeout(timeout time.Duration) *GetCameraErrorV2Params {
	return &GetCameraErrorV2Params{
		timeout: timeout,
	}
}

// NewGetCameraErrorV2ParamsWithContext creates a new GetCameraErrorV2Params object
// with the ability to set a context for a request.
func NewGetCameraErrorV2ParamsWithContext(ctx context.Context) *GetCameraErrorV2Params {
	return &GetCameraErrorV2Params{
		Context: ctx,
	}
}

// NewGetCameraErrorV2ParamsWithHTTPClient creates a new GetCameraErrorV2Params object
// with the ability to set a custom HTTPClient for a request.
func NewGetCameraErrorV2ParamsWithHTTPClient(client *http.Client) *GetCameraErrorV2Params {
	return &GetCameraErrorV2Params{
		HTTPClient: client,
	}
}

/* GetCameraErrorV2Params contains all the parameters to send to the API endpoint
   for the get camera error v2 operation.

   Typically these are written to a http.Request.
*/
type GetCameraErrorV2Params struct {

	/* StreamID.

	   StreamId of the IP Camera Streaming.
	*/
	StreamID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get camera error v2 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetCameraErrorV2Params) WithDefaults() *GetCameraErrorV2Params {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get camera error v2 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetCameraErrorV2Params) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get camera error v2 params
func (o *GetCameraErrorV2Params) WithTimeout(timeout time.Duration) *GetCameraErrorV2Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get camera error v2 params
func (o *GetCameraErrorV2Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get camera error v2 params
func (o *GetCameraErrorV2Params) WithContext(ctx context.Context) *GetCameraErrorV2Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get camera error v2 params
func (o *GetCameraErrorV2Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get camera error v2 params
func (o *GetCameraErrorV2Params) WithHTTPClient(client *http.Client) *GetCameraErrorV2Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get camera error v2 params
func (o *GetCameraErrorV2Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithStreamID adds the streamID to the get camera error v2 params
func (o *GetCameraErrorV2Params) WithStreamID(streamID string) *GetCameraErrorV2Params {
	o.SetStreamID(streamID)
	return o
}

// SetStreamID adds the streamId to the get camera error v2 params
func (o *GetCameraErrorV2Params) SetStreamID(streamID string) {
	o.StreamID = streamID
}

// WriteToRequest writes these params to a swagger request
func (o *GetCameraErrorV2Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param streamId
	if err := r.SetPathParam("streamId", o.StreamID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
