// Code generated by go-swagger;

package broadcast_rest_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"antmedia/models"
)

// ListTokensV2Reader is a Reader for the ListTokensV2 structure.
type ListTokensV2Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListTokensV2Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListTokensV2OK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewListTokensV2OK creates a ListTokensV2OK with default headers values
func NewListTokensV2OK() *ListTokensV2OK {
	return &ListTokensV2OK{}
}

/* ListTokensV2OK describes a response with status code 200, with default header values.

successful operation
*/
type ListTokensV2OK struct {
	Payload []*models.Token
}

func (o *ListTokensV2OK) Error() string {
	return fmt.Sprintf("[GET /v2/broadcasts/{id}/tokens/list/{offset}/{size}][%d] listTokensV2OK  %+v", 200, o.Payload)
}
func (o *ListTokensV2OK) GetPayload() []*models.Token {
	return o.Payload
}

func (o *ListTokensV2OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
