// Code generated by go-swagger;

package broadcast_rest_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/umutbasal/antmedia/models"
)

// RemoveEndpointReader is a Reader for the RemoveEndpoint structure.
type RemoveEndpointReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RemoveEndpointReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewRemoveEndpointOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewRemoveEndpointOK creates a RemoveEndpointOK with default headers values
func NewRemoveEndpointOK() *RemoveEndpointOK {
	return &RemoveEndpointOK{}
}

/* RemoveEndpointOK describes a response with status code 200, with default header values.

successful operation
*/
type RemoveEndpointOK struct {
	Payload *models.Result
}

func (o *RemoveEndpointOK) Error() string {
	return fmt.Sprintf("[DELETE /v2/broadcasts/{id}/endpoint][%d] removeEndpointOK  %+v", 200, o.Payload)
}
func (o *RemoveEndpointOK) GetPayload() *models.Result {
	return o.Payload
}

func (o *RemoveEndpointOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Result)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
