// Code generated by go-swagger; DO NOT EDIT.

package broadcast_rest_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewStopStreamingV2Params creates a new StopStreamingV2Params object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewStopStreamingV2Params() *StopStreamingV2Params {
	return &StopStreamingV2Params{
		timeout: cr.DefaultTimeout,
	}
}

// NewStopStreamingV2ParamsWithTimeout creates a new StopStreamingV2Params object
// with the ability to set a timeout on a request.
func NewStopStreamingV2ParamsWithTimeout(timeout time.Duration) *StopStreamingV2Params {
	return &StopStreamingV2Params{
		timeout: timeout,
	}
}

// NewStopStreamingV2ParamsWithContext creates a new StopStreamingV2Params object
// with the ability to set a context for a request.
func NewStopStreamingV2ParamsWithContext(ctx context.Context) *StopStreamingV2Params {
	return &StopStreamingV2Params{
		Context: ctx,
	}
}

// NewStopStreamingV2ParamsWithHTTPClient creates a new StopStreamingV2Params object
// with the ability to set a custom HTTPClient for a request.
func NewStopStreamingV2ParamsWithHTTPClient(client *http.Client) *StopStreamingV2Params {
	return &StopStreamingV2Params{
		HTTPClient: client,
	}
}

/* StopStreamingV2Params contains all the parameters to send to the API endpoint
   for the stop streaming v2 operation.

   Typically these are written to a http.Request.
*/
type StopStreamingV2Params struct {

	/* ID.

	   the id of the broadcast.
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the stop streaming v2 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *StopStreamingV2Params) WithDefaults() *StopStreamingV2Params {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the stop streaming v2 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *StopStreamingV2Params) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the stop streaming v2 params
func (o *StopStreamingV2Params) WithTimeout(timeout time.Duration) *StopStreamingV2Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the stop streaming v2 params
func (o *StopStreamingV2Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the stop streaming v2 params
func (o *StopStreamingV2Params) WithContext(ctx context.Context) *StopStreamingV2Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the stop streaming v2 params
func (o *StopStreamingV2Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the stop streaming v2 params
func (o *StopStreamingV2Params) WithHTTPClient(client *http.Client) *StopStreamingV2Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the stop streaming v2 params
func (o *StopStreamingV2Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the stop streaming v2 params
func (o *StopStreamingV2Params) WithID(id string) *StopStreamingV2Params {
	o.SetID(id)
	return o
}

// SetID adds the id to the stop streaming v2 params
func (o *StopStreamingV2Params) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *StopStreamingV2Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
