// Code generated by go-swagger;

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"

	"github.com/umutbasal/antmedia/client/management_rest_service"
	"github.com/umutbasal/antmedia/models"

	"github.com/go-openapi/swag"
	"github.com/spf13/cobra"
)

// makeOperationManagementRestServiceChangeServerSettingsCmd returns a cmd to handle operation changeServerSettings
func makeOperationManagementRestServiceChangeServerSettingsCmd() (*cobra.Command, error) {
	cmd := &cobra.Command{
		Use:   "changeServerSettings",
		Short: ``,
		RunE:  runOperationManagementRestServiceChangeServerSettings,
	}

	if err := registerOperationManagementRestServiceChangeServerSettingsParamFlags(cmd); err != nil {
		return nil, err
	}

	return cmd, nil
}

// runOperationManagementRestServiceChangeServerSettings uses cmd flags to call endpoint api
func runOperationManagementRestServiceChangeServerSettings(cmd *cobra.Command, args []string) error {
	appCli, err := makeClient(cmd, args)
	if err != nil {
		return err
	}
	// retrieve flag values from cmd and fill params
	params := management_rest_service.NewChangeServerSettingsParams()
	if err, _ := retrieveOperationManagementRestServiceChangeServerSettingsBodyFlag(params, "", cmd); err != nil {
		return err
	}
	if dryRun {

		logDebugf("dry-run flag specified. Skip sending request.")
		return nil
	}
	// make request and then print result
	msgStr, err := parseOperationManagementRestServiceChangeServerSettingsResult(appCli.ManagementRestService.ChangeServerSettings(params))
	if err != nil {
		return err
	}
	if !debug {

		fmt.Println(msgStr)
	}
	return nil
}

// registerOperationManagementRestServiceChangeServerSettingsParamFlags registers all flags needed to fill params
func registerOperationManagementRestServiceChangeServerSettingsParamFlags(cmd *cobra.Command) error {
	if err := registerOperationManagementRestServiceChangeServerSettingsBodyParamFlags("", cmd); err != nil {
		return err
	}
	return nil
}

func registerOperationManagementRestServiceChangeServerSettingsBodyParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	var bodyFlagName string
	if cmdPrefix == "" {
		bodyFlagName = "body"
	} else {
		bodyFlagName = fmt.Sprintf("%v.body", cmdPrefix)
	}

	_ = cmd.PersistentFlags().String(bodyFlagName, "", "Optional json string for [body]. Server settings")

	// add flags for body
	if err := registerModelServerSettingsFlags(0, "serverSettings", cmd); err != nil {
		return err
	}

	return nil
}

func retrieveOperationManagementRestServiceChangeServerSettingsBodyFlag(m *management_rest_service.ChangeServerSettingsParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("body") {
		// Read body string from cmd and unmarshal
		bodyValueStr, err := cmd.Flags().GetString("body")
		if err != nil {
			return err, false
		}

		bodyValue := models.ServerSettings{}
		if err := json.Unmarshal([]byte(bodyValueStr), &bodyValue); err != nil {
			return fmt.Errorf("cannot unmarshal body string in models.ServerSettings: %v", err), false
		}
		m.Body = &bodyValue
	}
	bodyValueModel := m.Body
	if swag.IsZero(bodyValueModel) {
		bodyValueModel = &models.ServerSettings{}
	}
	err, added := retrieveModelServerSettingsFlags(0, bodyValueModel, "serverSettings", cmd)
	if err != nil {
		return err, false
	}
	if added {
		m.Body = bodyValueModel
	}
	if dryRun && debug {

		bodyValueDebugBytes, err := json.Marshal(m.Body)
		if err != nil {
			return err, false
		}
		logDebugf("Body dry-run payload: %v", string(bodyValueDebugBytes))
	}
	retAdded = retAdded || added

	return nil, retAdded
}

// parseOperationManagementRestServiceChangeServerSettingsResult parses request result and return the string content
func parseOperationManagementRestServiceChangeServerSettingsResult(resp0 *management_rest_service.ChangeServerSettingsOK, respErr error) (string, error) {
	if respErr != nil {

		var iResp0 interface{} = respErr
		resp0, ok := iResp0.(*management_rest_service.ChangeServerSettingsOK)
		if ok {
			if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
				msgStr, err := json.Marshal(resp0.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		return "", respErr
	}

	if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
		msgStr, err := json.Marshal(resp0.Payload)
		if err != nil {
			return "", err
		}
		return string(msgStr), nil
	}

	return "", nil
}
