// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"antmedia/client/management_rest_service"
	"antmedia/models"
	"encoding/json"
	"fmt"

	"github.com/go-openapi/swag"
	"github.com/spf13/cobra"
)

// makeOperationManagementRestServiceChangeUserPasswordCmd returns a cmd to handle operation changeUserPassword
func makeOperationManagementRestServiceChangeUserPasswordCmd() (*cobra.Command, error) {
	cmd := &cobra.Command{
		Use:   "changeUserPassword",
		Short: ``,
		RunE:  runOperationManagementRestServiceChangeUserPassword,
	}

	if err := registerOperationManagementRestServiceChangeUserPasswordParamFlags(cmd); err != nil {
		return nil, err
	}

	return cmd, nil
}

// runOperationManagementRestServiceChangeUserPassword uses cmd flags to call endpoint api
func runOperationManagementRestServiceChangeUserPassword(cmd *cobra.Command, args []string) error {
	appCli, err := makeClient(cmd, args)
	if err != nil {
		return err
	}
	// retrieve flag values from cmd and fill params
	params := management_rest_service.NewChangeUserPasswordParams()
	if err, _ := retrieveOperationManagementRestServiceChangeUserPasswordBodyFlag(params, "", cmd); err != nil {
		return err
	}
	if dryRun {

		logDebugf("dry-run flag specified. Skip sending request.")
		return nil
	}
	// make request and then print result
	msgStr, err := parseOperationManagementRestServiceChangeUserPasswordResult(appCli.ManagementRestService.ChangeUserPassword(params))
	if err != nil {
		return err
	}
	if !debug {

		fmt.Println(msgStr)
	}
	return nil
}

// registerOperationManagementRestServiceChangeUserPasswordParamFlags registers all flags needed to fill params
func registerOperationManagementRestServiceChangeUserPasswordParamFlags(cmd *cobra.Command) error {
	if err := registerOperationManagementRestServiceChangeUserPasswordBodyParamFlags("", cmd); err != nil {
		return err
	}
	return nil
}

func registerOperationManagementRestServiceChangeUserPasswordBodyParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	var bodyFlagName string
	if cmdPrefix == "" {
		bodyFlagName = "body"
	} else {
		bodyFlagName = fmt.Sprintf("%v.body", cmdPrefix)
	}

	_ = cmd.PersistentFlags().String(bodyFlagName, "", "Optional json string for [body]. User object to change the password")

	// add flags for body
	if err := registerModelUserFlags(0, "user", cmd); err != nil {
		return err
	}

	return nil
}

func retrieveOperationManagementRestServiceChangeUserPasswordBodyFlag(m *management_rest_service.ChangeUserPasswordParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("body") {
		// Read body string from cmd and unmarshal
		bodyValueStr, err := cmd.Flags().GetString("body")
		if err != nil {
			return err, false
		}

		bodyValue := models.User{}
		if err := json.Unmarshal([]byte(bodyValueStr), &bodyValue); err != nil {
			return fmt.Errorf("cannot unmarshal body string in models.User: %v", err), false
		}
		m.Body = &bodyValue
	}
	bodyValueModel := m.Body
	if swag.IsZero(bodyValueModel) {
		bodyValueModel = &models.User{}
	}
	err, added := retrieveModelUserFlags(0, bodyValueModel, "user", cmd)
	if err != nil {
		return err, false
	}
	if added {
		m.Body = bodyValueModel
	}
	if dryRun && debug {

		bodyValueDebugBytes, err := json.Marshal(m.Body)
		if err != nil {
			return err, false
		}
		logDebugf("Body dry-run payload: %v", string(bodyValueDebugBytes))
	}
	retAdded = retAdded || added

	return nil, retAdded
}

// parseOperationManagementRestServiceChangeUserPasswordResult parses request result and return the string content
func parseOperationManagementRestServiceChangeUserPasswordResult(resp0 *management_rest_service.ChangeUserPasswordOK, respErr error) (string, error) {
	if respErr != nil {

		var iResp0 interface{} = respErr
		resp0, ok := iResp0.(*management_rest_service.ChangeUserPasswordOK)
		if ok {
			if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
				msgStr, err := json.Marshal(resp0.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		return "", respErr
	}

	if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
		msgStr, err := json.Marshal(resp0.Payload)
		if err != nil {
			return "", err
		}
		return string(msgStr), nil
	}

	return "", nil
}
