// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"antmedia/client/broadcast_rest_service"
	"antmedia/models"
	"encoding/json"
	"fmt"

	"github.com/go-openapi/swag"
	"github.com/spf13/cobra"
)

// makeOperationBroadcastRestServiceCreateConferenceRoomV2Cmd returns a cmd to handle operation createConferenceRoomV2
func makeOperationBroadcastRestServiceCreateConferenceRoomV2Cmd() (*cobra.Command, error) {
	cmd := &cobra.Command{
		Use:   "createConferenceRoomV2",
		Short: ``,
		RunE:  runOperationBroadcastRestServiceCreateConferenceRoomV2,
	}

	if err := registerOperationBroadcastRestServiceCreateConferenceRoomV2ParamFlags(cmd); err != nil {
		return nil, err
	}

	return cmd, nil
}

// runOperationBroadcastRestServiceCreateConferenceRoomV2 uses cmd flags to call endpoint api
func runOperationBroadcastRestServiceCreateConferenceRoomV2(cmd *cobra.Command, args []string) error {
	appCli, err := makeClient(cmd, args)
	if err != nil {
		return err
	}
	// retrieve flag values from cmd and fill params
	params := broadcast_rest_service.NewCreateConferenceRoomV2Params()
	if err, _ := retrieveOperationBroadcastRestServiceCreateConferenceRoomV2BodyFlag(params, "", cmd); err != nil {
		return err
	}
	if dryRun {

		logDebugf("dry-run flag specified. Skip sending request.")
		return nil
	}
	// make request and then print result
	msgStr, err := parseOperationBroadcastRestServiceCreateConferenceRoomV2Result(appCli.BroadcastRestService.CreateConferenceRoomV2(params))
	if err != nil {
		return err
	}
	if !debug {

		fmt.Println(msgStr)
	}
	return nil
}

// registerOperationBroadcastRestServiceCreateConferenceRoomV2ParamFlags registers all flags needed to fill params
func registerOperationBroadcastRestServiceCreateConferenceRoomV2ParamFlags(cmd *cobra.Command) error {
	if err := registerOperationBroadcastRestServiceCreateConferenceRoomV2BodyParamFlags("", cmd); err != nil {
		return err
	}
	return nil
}

func registerOperationBroadcastRestServiceCreateConferenceRoomV2BodyParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	var bodyFlagName string
	if cmdPrefix == "" {
		bodyFlagName = "body"
	} else {
		bodyFlagName = fmt.Sprintf("%v.body", cmdPrefix)
	}

	_ = cmd.PersistentFlags().String(bodyFlagName, "", "Optional json string for [body]. Conference Room object with start and end date")

	// add flags for body
	if err := registerModelConferenceRoomFlags(0, "conferenceRoom", cmd); err != nil {
		return err
	}

	return nil
}

func retrieveOperationBroadcastRestServiceCreateConferenceRoomV2BodyFlag(m *broadcast_rest_service.CreateConferenceRoomV2Params, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("body") {
		// Read body string from cmd and unmarshal
		bodyValueStr, err := cmd.Flags().GetString("body")
		if err != nil {
			return err, false
		}

		bodyValue := models.ConferenceRoom{}
		if err := json.Unmarshal([]byte(bodyValueStr), &bodyValue); err != nil {
			return fmt.Errorf("cannot unmarshal body string in models.ConferenceRoom: %v", err), false
		}
		m.Body = &bodyValue
	}
	bodyValueModel := m.Body
	if swag.IsZero(bodyValueModel) {
		bodyValueModel = &models.ConferenceRoom{}
	}
	err, added := retrieveModelConferenceRoomFlags(0, bodyValueModel, "conferenceRoom", cmd)
	if err != nil {
		return err, false
	}
	if added {
		m.Body = bodyValueModel
	}
	if dryRun && debug {

		bodyValueDebugBytes, err := json.Marshal(m.Body)
		if err != nil {
			return err, false
		}
		logDebugf("Body dry-run payload: %v", string(bodyValueDebugBytes))
	}
	retAdded = retAdded || added

	return nil, retAdded
}

// parseOperationBroadcastRestServiceCreateConferenceRoomV2Result parses request result and return the string content
func parseOperationBroadcastRestServiceCreateConferenceRoomV2Result(resp0 *broadcast_rest_service.CreateConferenceRoomV2OK, respErr error) (string, error) {
	if respErr != nil {

		var iResp0 interface{} = respErr
		resp0, ok := iResp0.(*broadcast_rest_service.CreateConferenceRoomV2OK)
		if ok {
			if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
				msgStr, err := json.Marshal(resp0.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp1 interface{} = respErr
		resp1, ok := iResp1.(*broadcast_rest_service.CreateConferenceRoomV2BadRequest)
		if ok {
			if !swag.IsZero(resp1) && !swag.IsZero(resp1.Payload) {
				msgStr, err := json.Marshal(resp1.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		return "", respErr
	}

	if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
		msgStr, err := json.Marshal(resp0.Payload)
		if err != nil {
			return "", err
		}
		return string(msgStr), nil
	}

	return "", nil
}
