// Code generated by go-swagger;

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"

	"github.com/umutbasal/antmedia/client/broadcast_rest_service"

	"github.com/go-openapi/swag"
	"github.com/spf13/cobra"
)

// makeOperationBroadcastRestServiceFilterBroadcastListV2Cmd returns a cmd to handle operation filterBroadcastListV2
func makeOperationBroadcastRestServiceFilterBroadcastListV2Cmd() (*cobra.Command, error) {
	cmd := &cobra.Command{
		Use:   "filterBroadcastListV2",
		Short: ``,
		RunE:  runOperationBroadcastRestServiceFilterBroadcastListV2,
	}

	if err := registerOperationBroadcastRestServiceFilterBroadcastListV2ParamFlags(cmd); err != nil {
		return nil, err
	}

	return cmd, nil
}

// runOperationBroadcastRestServiceFilterBroadcastListV2 uses cmd flags to call endpoint api
func runOperationBroadcastRestServiceFilterBroadcastListV2(cmd *cobra.Command, args []string) error {
	appCli, err := makeClient(cmd, args)
	if err != nil {
		return err
	}
	// retrieve flag values from cmd and fill params
	params := broadcast_rest_service.NewFilterBroadcastListV2Params()
	if err, _ := retrieveOperationBroadcastRestServiceFilterBroadcastListV2OffsetFlag(params, "", cmd); err != nil {
		return err
	}
	if err, _ := retrieveOperationBroadcastRestServiceFilterBroadcastListV2OrderByFlag(params, "", cmd); err != nil {
		return err
	}
	if err, _ := retrieveOperationBroadcastRestServiceFilterBroadcastListV2SizeFlag(params, "", cmd); err != nil {
		return err
	}
	if err, _ := retrieveOperationBroadcastRestServiceFilterBroadcastListV2SortByFlag(params, "", cmd); err != nil {
		return err
	}
	if err, _ := retrieveOperationBroadcastRestServiceFilterBroadcastListV2TypeFlag(params, "", cmd); err != nil {
		return err
	}
	if dryRun {

		logDebugf("dry-run flag specified. Skip sending request.")
		return nil
	}
	// make request and then print result
	msgStr, err := parseOperationBroadcastRestServiceFilterBroadcastListV2Result(appCli.BroadcastRestService.FilterBroadcastListV2(params))
	if err != nil {
		return err
	}
	if !debug {

		fmt.Println(msgStr)
	}
	return nil
}

// registerOperationBroadcastRestServiceFilterBroadcastListV2ParamFlags registers all flags needed to fill params
func registerOperationBroadcastRestServiceFilterBroadcastListV2ParamFlags(cmd *cobra.Command) error {
	if err := registerOperationBroadcastRestServiceFilterBroadcastListV2OffsetParamFlags("", cmd); err != nil {
		return err
	}
	if err := registerOperationBroadcastRestServiceFilterBroadcastListV2OrderByParamFlags("", cmd); err != nil {
		return err
	}
	if err := registerOperationBroadcastRestServiceFilterBroadcastListV2SizeParamFlags("", cmd); err != nil {
		return err
	}
	if err := registerOperationBroadcastRestServiceFilterBroadcastListV2SortByParamFlags("", cmd); err != nil {
		return err
	}
	if err := registerOperationBroadcastRestServiceFilterBroadcastListV2TypeParamFlags("", cmd); err != nil {
		return err
	}
	return nil
}

func registerOperationBroadcastRestServiceFilterBroadcastListV2OffsetParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	offsetDescription := `Required. starting point of the list`

	var offsetFlagName string
	if cmdPrefix == "" {
		offsetFlagName = "offset"
	} else {
		offsetFlagName = fmt.Sprintf("%v.offset", cmdPrefix)
	}

	var offsetFlagDefault int32

	_ = cmd.PersistentFlags().Int32(offsetFlagName, offsetFlagDefault, offsetDescription)

	return nil
}
func registerOperationBroadcastRestServiceFilterBroadcastListV2OrderByParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	orderByDescription := `asc for Ascending, desc Descending order`

	var orderByFlagName string
	if cmdPrefix == "" {
		orderByFlagName = "order_by"
	} else {
		orderByFlagName = fmt.Sprintf("%v.order_by", cmdPrefix)
	}

	var orderByFlagDefault string

	_ = cmd.PersistentFlags().String(orderByFlagName, orderByFlagDefault, orderByDescription)

	return nil
}
func registerOperationBroadcastRestServiceFilterBroadcastListV2SizeParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	sizeDescription := `Required. size of the return list (max:50 )`

	var sizeFlagName string
	if cmdPrefix == "" {
		sizeFlagName = "size"
	} else {
		sizeFlagName = fmt.Sprintf("%v.size", cmdPrefix)
	}

	var sizeFlagDefault int32

	_ = cmd.PersistentFlags().Int32(sizeFlagName, sizeFlagDefault, sizeDescription)

	return nil
}
func registerOperationBroadcastRestServiceFilterBroadcastListV2SortByParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	sortByDescription := `field to sort`

	var sortByFlagName string
	if cmdPrefix == "" {
		sortByFlagName = "sort_by"
	} else {
		sortByFlagName = fmt.Sprintf("%v.sort_by", cmdPrefix)
	}

	var sortByFlagDefault string

	_ = cmd.PersistentFlags().String(sortByFlagName, sortByFlagDefault, sortByDescription)

	return nil
}
func registerOperationBroadcastRestServiceFilterBroadcastListV2TypeParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	typeDescription := `Required. type of the stream. Possible values are "liveStream", "ipCamera", "streamSource", "VoD"`

	var typeFlagName string
	if cmdPrefix == "" {
		typeFlagName = "type"
	} else {
		typeFlagName = fmt.Sprintf("%v.type", cmdPrefix)
	}

	var typeFlagDefault string

	_ = cmd.PersistentFlags().String(typeFlagName, typeFlagDefault, typeDescription)

	return nil
}

func retrieveOperationBroadcastRestServiceFilterBroadcastListV2OffsetFlag(m *broadcast_rest_service.FilterBroadcastListV2Params, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("offset") {

		var offsetFlagName string
		if cmdPrefix == "" {
			offsetFlagName = "offset"
		} else {
			offsetFlagName = fmt.Sprintf("%v.offset", cmdPrefix)
		}

		offsetFlagValue, err := cmd.Flags().GetInt32(offsetFlagName)
		if err != nil {
			return err, false
		}
		m.Offset = offsetFlagValue

	}
	return nil, retAdded
}
func retrieveOperationBroadcastRestServiceFilterBroadcastListV2OrderByFlag(m *broadcast_rest_service.FilterBroadcastListV2Params, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("order_by") {

		var orderByFlagName string
		if cmdPrefix == "" {
			orderByFlagName = "order_by"
		} else {
			orderByFlagName = fmt.Sprintf("%v.order_by", cmdPrefix)
		}

		orderByFlagValue, err := cmd.Flags().GetString(orderByFlagName)
		if err != nil {
			return err, false
		}
		m.OrderBy = &orderByFlagValue

	}
	return nil, retAdded
}
func retrieveOperationBroadcastRestServiceFilterBroadcastListV2SizeFlag(m *broadcast_rest_service.FilterBroadcastListV2Params, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("size") {

		var sizeFlagName string
		if cmdPrefix == "" {
			sizeFlagName = "size"
		} else {
			sizeFlagName = fmt.Sprintf("%v.size", cmdPrefix)
		}

		sizeFlagValue, err := cmd.Flags().GetInt32(sizeFlagName)
		if err != nil {
			return err, false
		}
		m.Size = sizeFlagValue

	}
	return nil, retAdded
}
func retrieveOperationBroadcastRestServiceFilterBroadcastListV2SortByFlag(m *broadcast_rest_service.FilterBroadcastListV2Params, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("sort_by") {

		var sortByFlagName string
		if cmdPrefix == "" {
			sortByFlagName = "sort_by"
		} else {
			sortByFlagName = fmt.Sprintf("%v.sort_by", cmdPrefix)
		}

		sortByFlagValue, err := cmd.Flags().GetString(sortByFlagName)
		if err != nil {
			return err, false
		}
		m.SortBy = &sortByFlagValue

	}
	return nil, retAdded
}
func retrieveOperationBroadcastRestServiceFilterBroadcastListV2TypeFlag(m *broadcast_rest_service.FilterBroadcastListV2Params, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("type") {

		var typeFlagName string
		if cmdPrefix == "" {
			typeFlagName = "type"
		} else {
			typeFlagName = fmt.Sprintf("%v.type", cmdPrefix)
		}

		typeFlagValue, err := cmd.Flags().GetString(typeFlagName)
		if err != nil {
			return err, false
		}
		m.Type = typeFlagValue

	}
	return nil, retAdded
}

// parseOperationBroadcastRestServiceFilterBroadcastListV2Result parses request result and return the string content
func parseOperationBroadcastRestServiceFilterBroadcastListV2Result(resp0 *broadcast_rest_service.FilterBroadcastListV2OK, respErr error) (string, error) {
	if respErr != nil {

		var iResp0 interface{} = respErr
		resp0, ok := iResp0.(*broadcast_rest_service.FilterBroadcastListV2OK)
		if ok {
			if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
				msgStr, err := json.Marshal(resp0.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		return "", respErr
	}

	if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
		msgStr, err := json.Marshal(resp0.Payload)
		if err != nil {
			return "", err
		}
		return string(msgStr), nil
	}

	return "", nil
}
