// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"antmedia/client/vo_d_rest_service"
	"encoding/json"
	"fmt"

	"github.com/go-openapi/swag"
	"github.com/spf13/cobra"
)

// makeOperationVodRestServiceGetVoDCmd returns a cmd to handle operation getVoD
func makeOperationVodRestServiceGetVoDCmd() (*cobra.Command, error) {
	cmd := &cobra.Command{
		Use:   "getVoD",
		Short: ``,
		RunE:  runOperationVodRestServiceGetVoD,
	}

	if err := registerOperationVodRestServiceGetVoDParamFlags(cmd); err != nil {
		return nil, err
	}

	return cmd, nil
}

// runOperationVodRestServiceGetVoD uses cmd flags to call endpoint api
func runOperationVodRestServiceGetVoD(cmd *cobra.Command, args []string) error {
	appCli, err := makeClient(cmd, args)
	if err != nil {
		return err
	}
	// retrieve flag values from cmd and fill params
	params := vo_d_rest_service.NewGetVoDParams()
	if err, _ := retrieveOperationVodRestServiceGetVoDIDFlag(params, "", cmd); err != nil {
		return err
	}
	if dryRun {

		logDebugf("dry-run flag specified. Skip sending request.")
		return nil
	}
	// make request and then print result
	msgStr, err := parseOperationVodRestServiceGetVoDResult(appCli.VodRestService.GetVoD(params))
	if err != nil {
		return err
	}
	if !debug {

		fmt.Println(msgStr)
	}
	return nil
}

// registerOperationVodRestServiceGetVoDParamFlags registers all flags needed to fill params
func registerOperationVodRestServiceGetVoDParamFlags(cmd *cobra.Command) error {
	if err := registerOperationVodRestServiceGetVoDIDParamFlags("", cmd); err != nil {
		return err
	}
	return nil
}

func registerOperationVodRestServiceGetVoDIDParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	idDescription := `Required. id of the VoD`

	var idFlagName string
	if cmdPrefix == "" {
		idFlagName = "id"
	} else {
		idFlagName = fmt.Sprintf("%v.id", cmdPrefix)
	}

	var idFlagDefault string

	_ = cmd.PersistentFlags().String(idFlagName, idFlagDefault, idDescription)

	return nil
}

func retrieveOperationVodRestServiceGetVoDIDFlag(m *vo_d_rest_service.GetVoDParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("id") {

		var idFlagName string
		if cmdPrefix == "" {
			idFlagName = "id"
		} else {
			idFlagName = fmt.Sprintf("%v.id", cmdPrefix)
		}

		idFlagValue, err := cmd.Flags().GetString(idFlagName)
		if err != nil {
			return err, false
		}
		m.ID = idFlagValue

	}
	return nil, retAdded
}

// parseOperationVodRestServiceGetVoDResult parses request result and return the string content
func parseOperationVodRestServiceGetVoDResult(resp0 *vo_d_rest_service.GetVoDOK, respErr error) (string, error) {
	if respErr != nil {

		var iResp0 interface{} = respErr
		resp0, ok := iResp0.(*vo_d_rest_service.GetVoDOK)
		if ok {
			if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
				msgStr, err := json.Marshal(resp0.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		return "", respErr
	}

	if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
		msgStr, err := json.Marshal(resp0.Payload)
		if err != nil {
			return "", err
		}
		return string(msgStr), nil
	}

	return "", nil
}
