// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"antmedia/client/broadcast_rest_service"
	"encoding/json"
	"fmt"

	"github.com/go-openapi/swag"
	"github.com/spf13/cobra"
)

// makeOperationBroadcastRestServiceRemoveEndpointCmd returns a cmd to handle operation removeEndpoint
func makeOperationBroadcastRestServiceRemoveEndpointCmd() (*cobra.Command, error) {
	cmd := &cobra.Command{
		Use:   "removeEndpoint",
		Short: ``,
		RunE:  runOperationBroadcastRestServiceRemoveEndpoint,
	}

	if err := registerOperationBroadcastRestServiceRemoveEndpointParamFlags(cmd); err != nil {
		return nil, err
	}

	return cmd, nil
}

// runOperationBroadcastRestServiceRemoveEndpoint uses cmd flags to call endpoint api
func runOperationBroadcastRestServiceRemoveEndpoint(cmd *cobra.Command, args []string) error {
	appCli, err := makeClient(cmd, args)
	if err != nil {
		return err
	}
	// retrieve flag values from cmd and fill params
	params := broadcast_rest_service.NewRemoveEndpointParams()
	if err, _ := retrieveOperationBroadcastRestServiceRemoveEndpointIDFlag(params, "", cmd); err != nil {
		return err
	}
	if err, _ := retrieveOperationBroadcastRestServiceRemoveEndpointRtmpURLFlag(params, "", cmd); err != nil {
		return err
	}
	if dryRun {

		logDebugf("dry-run flag specified. Skip sending request.")
		return nil
	}
	// make request and then print result
	msgStr, err := parseOperationBroadcastRestServiceRemoveEndpointResult(appCli.BroadcastRestService.RemoveEndpoint(params))
	if err != nil {
		return err
	}
	if !debug {

		fmt.Println(msgStr)
	}
	return nil
}

// registerOperationBroadcastRestServiceRemoveEndpointParamFlags registers all flags needed to fill params
func registerOperationBroadcastRestServiceRemoveEndpointParamFlags(cmd *cobra.Command) error {
	if err := registerOperationBroadcastRestServiceRemoveEndpointIDParamFlags("", cmd); err != nil {
		return err
	}
	if err := registerOperationBroadcastRestServiceRemoveEndpointRtmpURLParamFlags("", cmd); err != nil {
		return err
	}
	return nil
}

func registerOperationBroadcastRestServiceRemoveEndpointIDParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	idDescription := `Required. Broadcast id`

	var idFlagName string
	if cmdPrefix == "" {
		idFlagName = "id"
	} else {
		idFlagName = fmt.Sprintf("%v.id", cmdPrefix)
	}

	var idFlagDefault string

	_ = cmd.PersistentFlags().String(idFlagName, idFlagDefault, idDescription)

	return nil
}
func registerOperationBroadcastRestServiceRemoveEndpointRtmpURLParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	rtmpUrlDescription := `Required. RTMP url of the endpoint that will be stopped.`

	var rtmpUrlFlagName string
	if cmdPrefix == "" {
		rtmpUrlFlagName = "rtmpUrl"
	} else {
		rtmpUrlFlagName = fmt.Sprintf("%v.rtmpUrl", cmdPrefix)
	}

	var rtmpUrlFlagDefault string

	_ = cmd.PersistentFlags().String(rtmpUrlFlagName, rtmpUrlFlagDefault, rtmpUrlDescription)

	return nil
}

func retrieveOperationBroadcastRestServiceRemoveEndpointIDFlag(m *broadcast_rest_service.RemoveEndpointParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("id") {

		var idFlagName string
		if cmdPrefix == "" {
			idFlagName = "id"
		} else {
			idFlagName = fmt.Sprintf("%v.id", cmdPrefix)
		}

		idFlagValue, err := cmd.Flags().GetString(idFlagName)
		if err != nil {
			return err, false
		}
		m.ID = idFlagValue

	}
	return nil, retAdded
}
func retrieveOperationBroadcastRestServiceRemoveEndpointRtmpURLFlag(m *broadcast_rest_service.RemoveEndpointParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("rtmpUrl") {

		var rtmpUrlFlagName string
		if cmdPrefix == "" {
			rtmpUrlFlagName = "rtmpUrl"
		} else {
			rtmpUrlFlagName = fmt.Sprintf("%v.rtmpUrl", cmdPrefix)
		}

		rtmpUrlFlagValue, err := cmd.Flags().GetString(rtmpUrlFlagName)
		if err != nil {
			return err, false
		}
		m.RtmpURL = rtmpUrlFlagValue

	}
	return nil, retAdded
}

// parseOperationBroadcastRestServiceRemoveEndpointResult parses request result and return the string content
func parseOperationBroadcastRestServiceRemoveEndpointResult(resp0 *broadcast_rest_service.RemoveEndpointOK, respErr error) (string, error) {
	if respErr != nil {

		var iResp0 interface{} = respErr
		resp0, ok := iResp0.(*broadcast_rest_service.RemoveEndpointOK)
		if ok {
			if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
				msgStr, err := json.Marshal(resp0.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		return "", respErr
	}

	if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
		msgStr, err := json.Marshal(resp0.Payload)
		if err != nil {
			return "", err
		}
		return string(msgStr), nil
	}

	return "", nil
}
