// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"antmedia/models"
	"fmt"

	"github.com/spf13/cobra"
)

// Schema cli for SchemeRegistry

// register flags to command
func registerModelSchemeRegistryFlags(depth int, cmdPrefix string, cmd *cobra.Command) error {

	if err := registerSchemeRegistrySchemeNames(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	return nil
}

func registerSchemeRegistrySchemeNames(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	// warning: schemeNames []string array type is not supported by go-swagger cli yet

	return nil
}

// retrieve flags from commands, and set value in model. Return true if any flag is passed by user to fill model field.
func retrieveModelSchemeRegistryFlags(depth int, m *models.SchemeRegistry, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false

	err, schemeNamesAdded := retrieveSchemeRegistrySchemeNamesFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || schemeNamesAdded

	return nil, retAdded
}

func retrieveSchemeRegistrySchemeNamesFlags(depth int, m *models.SchemeRegistry, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	schemeNamesFlagName := fmt.Sprintf("%v.schemeNames", cmdPrefix)
	if cmd.Flags().Changed(schemeNamesFlagName) {
		// warning: schemeNames array type []string is not supported by go-swagger cli yet
	}

	return nil, retAdded
}
