// Code generated by go-swagger;

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"antmedia/client/broadcast_rest_service"
	"encoding/json"
	"fmt"

	"github.com/go-openapi/swag"
	"github.com/spf13/cobra"
)

// makeOperationBroadcastRestServiceStartStreamSourceV2Cmd returns a cmd to handle operation startStreamSourceV2
func makeOperationBroadcastRestServiceStartStreamSourceV2Cmd() (*cobra.Command, error) {
	cmd := &cobra.Command{
		Use:   "startStreamSourceV2",
		Short: ``,
		RunE:  runOperationBroadcastRestServiceStartStreamSourceV2,
	}

	if err := registerOperationBroadcastRestServiceStartStreamSourceV2ParamFlags(cmd); err != nil {
		return nil, err
	}

	return cmd, nil
}

// runOperationBroadcastRestServiceStartStreamSourceV2 uses cmd flags to call endpoint api
func runOperationBroadcastRestServiceStartStreamSourceV2(cmd *cobra.Command, args []string) error {
	appCli, err := makeClient(cmd, args)
	if err != nil {
		return err
	}
	// retrieve flag values from cmd and fill params
	params := broadcast_rest_service.NewStartStreamSourceV2Params()
	if err, _ := retrieveOperationBroadcastRestServiceStartStreamSourceV2IDFlag(params, "", cmd); err != nil {
		return err
	}
	if dryRun {

		logDebugf("dry-run flag specified. Skip sending request.")
		return nil
	}
	// make request and then print result
	msgStr, err := parseOperationBroadcastRestServiceStartStreamSourceV2Result(appCli.BroadcastRestService.StartStreamSourceV2(params))
	if err != nil {
		return err
	}
	if !debug {

		fmt.Println(msgStr)
	}
	return nil
}

// registerOperationBroadcastRestServiceStartStreamSourceV2ParamFlags registers all flags needed to fill params
func registerOperationBroadcastRestServiceStartStreamSourceV2ParamFlags(cmd *cobra.Command) error {
	if err := registerOperationBroadcastRestServiceStartStreamSourceV2IDParamFlags("", cmd); err != nil {
		return err
	}
	return nil
}

func registerOperationBroadcastRestServiceStartStreamSourceV2IDParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	idDescription := `Required. the id of the stream. The broadcast type should be IP Camera or Stream Source otherwise it does not work`

	var idFlagName string
	if cmdPrefix == "" {
		idFlagName = "id"
	} else {
		idFlagName = fmt.Sprintf("%v.id", cmdPrefix)
	}

	var idFlagDefault string

	_ = cmd.PersistentFlags().String(idFlagName, idFlagDefault, idDescription)

	return nil
}

func retrieveOperationBroadcastRestServiceStartStreamSourceV2IDFlag(m *broadcast_rest_service.StartStreamSourceV2Params, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("id") {

		var idFlagName string
		if cmdPrefix == "" {
			idFlagName = "id"
		} else {
			idFlagName = fmt.Sprintf("%v.id", cmdPrefix)
		}

		idFlagValue, err := cmd.Flags().GetString(idFlagName)
		if err != nil {
			return err, false
		}
		m.ID = idFlagValue

	}
	return nil, retAdded
}

// parseOperationBroadcastRestServiceStartStreamSourceV2Result parses request result and return the string content
func parseOperationBroadcastRestServiceStartStreamSourceV2Result(resp0 *broadcast_rest_service.StartStreamSourceV2OK, respErr error) (string, error) {
	if respErr != nil {

		var iResp0 interface{} = respErr
		resp0, ok := iResp0.(*broadcast_rest_service.StartStreamSourceV2OK)
		if ok {
			if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
				msgStr, err := json.Marshal(resp0.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		return "", respErr
	}

	if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
		msgStr, err := json.Marshal(resp0.Payload)
		if err != nil {
			return "", err
		}
		return string(msgStr), nil
	}

	return "", nil
}
