// Code generated by go-swagger; DO NOT EDIT.

package vo_d_rest_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"antmedia/models"
)

// GetVoDReader is a Reader for the GetVoD structure.
type GetVoDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetVoDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetVoDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetVoDOK creates a GetVoDOK with default headers values
func NewGetVoDOK() *GetVoDOK {
	return &GetVoDOK{}
}

/* GetVoDOK describes a response with status code 200, with default header values.

successful operation
*/
type GetVoDOK struct {
	Payload *models.VoD
}

func (o *GetVoDOK) Error() string {
	return fmt.Sprintf("[GET /v2/vods/{id}][%d] getVoDOK  %+v", 200, o.Payload)
}
func (o *GetVoDOK) GetPayload() *models.VoD {
	return o.Payload
}

func (o *GetVoDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.VoD)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
