// Code generated by go-swagger;

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetShutdownStatusParams creates a new GetShutdownStatusParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetShutdownStatusParams() *GetShutdownStatusParams {
	return &GetShutdownStatusParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetShutdownStatusParamsWithTimeout creates a new GetShutdownStatusParams object
// with the ability to set a timeout on a request.
func NewGetShutdownStatusParamsWithTimeout(timeout time.Duration) *GetShutdownStatusParams {
	return &GetShutdownStatusParams{
		timeout: timeout,
	}
}

// NewGetShutdownStatusParamsWithContext creates a new GetShutdownStatusParams object
// with the ability to set a context for a request.
func NewGetShutdownStatusParamsWithContext(ctx context.Context) *GetShutdownStatusParams {
	return &GetShutdownStatusParams{
		Context: ctx,
	}
}

// NewGetShutdownStatusParamsWithHTTPClient creates a new GetShutdownStatusParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetShutdownStatusParamsWithHTTPClient(client *http.Client) *GetShutdownStatusParams {
	return &GetShutdownStatusParams{
		HTTPClient: client,
	}
}

/* GetShutdownStatusParams contains all the parameters to send to the API endpoint
   for the get shutdown status operation.

   Typically these are written to a http.Request.
*/
type GetShutdownStatusParams struct {

	// AppNames.
	AppNames *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get shutdown status params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetShutdownStatusParams) WithDefaults() *GetShutdownStatusParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get shutdown status params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetShutdownStatusParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get shutdown status params
func (o *GetShutdownStatusParams) WithTimeout(timeout time.Duration) *GetShutdownStatusParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get shutdown status params
func (o *GetShutdownStatusParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get shutdown status params
func (o *GetShutdownStatusParams) WithContext(ctx context.Context) *GetShutdownStatusParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get shutdown status params
func (o *GetShutdownStatusParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get shutdown status params
func (o *GetShutdownStatusParams) WithHTTPClient(client *http.Client) *GetShutdownStatusParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get shutdown status params
func (o *GetShutdownStatusParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAppNames adds the appNames to the get shutdown status params
func (o *GetShutdownStatusParams) WithAppNames(appNames *string) *GetShutdownStatusParams {
	o.SetAppNames(appNames)
	return o
}

// SetAppNames adds the appNames to the get shutdown status params
func (o *GetShutdownStatusParams) SetAppNames(appNames *string) {
	o.AppNames = appNames
}

// WriteToRequest writes these params to a swagger request
func (o *GetShutdownStatusParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.AppNames != nil {

		// query param appNames
		var qrAppNames string

		if o.AppNames != nil {
			qrAppNames = *o.AppNames
		}
		qAppNames := qrAppNames
		if qAppNames != "" {

			if err := r.SetQueryParam("appNames", qAppNames); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
