// Code generated by go-swagger;

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ConferenceRoom The Conference Room class
//
// swagger:model ConferenceRoom
type ConferenceRoom struct {

	// The end date of the Conference Room. It's unix timestamp in seconds
	EndDate int64 `json:"endDate,omitempty"`

	// Conference Room Mode: legacy | mcu | multi-track
	Mode string `json:"mode,omitempty"`

	// The id of the Conference Room
	RoomID string `json:"roomId,omitempty"`

	// The list of streams in the Conference Room
	RoomStreamList []string `json:"roomStreamList"`

	// The start date of the Conference Room. It's unix timestamp in seconds.
	StartDate int64 `json:"startDate,omitempty"`
}

// Validate validates this conference room
func (m *ConferenceRoom) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this conference room based on context it is used
func (m *ConferenceRoom) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ConferenceRoom) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ConferenceRoom) UnmarshalBinary(b []byte) error {
	var res ConferenceRoom
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
