// Code generated by go-swagger;

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// IteratorIGlobalScope iterator i global scope
//
// swagger:model IteratorIGlobalScope
type IteratorIGlobalScope interface{}
