// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Licence licence
//
// swagger:model Licence
type Licence struct {

	// end date
	EndDate string `json:"endDate,omitempty"`

	// licence count
	LicenceCount string `json:"licenceCount,omitempty"`

	// licence Id
	LicenceID string `json:"licenceId,omitempty"`

	// owner
	Owner string `json:"owner,omitempty"`

	// start date
	StartDate string `json:"startDate,omitempty"`

	// status
	Status string `json:"status,omitempty"`

	// type
	Type string `json:"type,omitempty"`
}

// Validate validates this licence
func (m *Licence) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this licence based on context it is used
func (m *Licence) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Licence) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Licence) UnmarshalBinary(b []byte) error {
	var res Licence
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
