// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Pointer pointer
//
// swagger:model Pointer
type Pointer struct {

	// null
	Null bool `json:"null,omitempty"`

	// pointer
	Pointer *Pointer `json:"pointer,omitempty"`
}

// Validate validates this pointer
func (m *Pointer) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePointer(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Pointer) validatePointer(formats strfmt.Registry) error {
	if swag.IsZero(m.Pointer) { // not required
		return nil
	}

	if m.Pointer != nil {
		if err := m.Pointer.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("pointer")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("pointer")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this pointer based on the context it is used
func (m *Pointer) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidatePointer(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Pointer) contextValidatePointer(ctx context.Context, formats strfmt.Registry) error {

	if m.Pointer != nil {
		if err := m.Pointer.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("pointer")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("pointer")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Pointer) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Pointer) UnmarshalBinary(b []byte) error {
	var res Pointer
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
