// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// RTMPToWebRTCStats r t m p to web r t c stats
//
// swagger:model RTMPToWebRTCStats
type RTMPToWebRTCStats struct {

	// absolute time ms
	AbsoluteTimeMs int64 `json:"absoluteTimeMs,omitempty"`

	// absolute total ingest time
	AbsoluteTotalIngestTime int64 `json:"absoluteTotalIngestTime,omitempty"`

	// absoute total latency until r t p packetizing time ms
	AbsouteTotalLatencyUntilRTPPacketizingTimeMs int64 `json:"absouteTotalLatencyUntilRTPPacketizingTimeMs,omitempty"`

	// capture time ms
	CaptureTimeMs int64 `json:"captureTimeMs,omitempty"`

	// encoder count
	EncoderCount int32 `json:"encoderCount,omitempty"`

	// frame Id
	FrameID int64 `json:"frameId,omitempty"`

	// stream Id
	StreamID string `json:"streamId,omitempty"`

	// total decoded video frame count
	TotalDecodedVideoFrameCount int64 `json:"totalDecodedVideoFrameCount,omitempty"`

	// total delivered video packet count
	TotalDeliveredVideoPacketCount int64 `json:"totalDeliveredVideoPacketCount,omitempty"`

	// total encoded video packet count
	TotalEncodedVideoPacketCount int64 `json:"totalEncodedVideoPacketCount,omitempty"`

	// total ingested video packet count
	TotalIngestedVideoPacketCount int64 `json:"totalIngestedVideoPacketCount,omitempty"`

	// total video decode time
	TotalVideoDecodeTime int64 `json:"totalVideoDecodeTime,omitempty"`

	// total video delivery time
	TotalVideoDeliveryTime int64 `json:"totalVideoDeliveryTime,omitempty"`

	// total video encode queue time
	TotalVideoEncodeQueueTime int64 `json:"totalVideoEncodeQueueTime,omitempty"`

	// total video encode time
	TotalVideoEncodeTime int64 `json:"totalVideoEncodeTime,omitempty"`

	// total video ingest time
	TotalVideoIngestTime int64 `json:"totalVideoIngestTime,omitempty"`
}

// Validate validates this r t m p to web r t c stats
func (m *RTMPToWebRTCStats) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this r t m p to web r t c stats based on context it is used
func (m *RTMPToWebRTCStats) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RTMPToWebRTCStats) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RTMPToWebRTCStats) UnmarshalBinary(b []byte) error {
	var res RTMPToWebRTCStats
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
