// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// TensorFlowObject The TensorFlow detected object class
//
// swagger:model TensorFlowObject
type TensorFlowObject struct {

	// the time of the detected object
	DetectionTime int64 `json:"detectionTime,omitempty"`

	// the id of the detected image
	ImageID string `json:"imageId,omitempty"`

	// the x coordinate of lower-right corner of detected object frame
	MaxX float64 `json:"maxX,omitempty"`

	// the y coordinate of lower-right corner of detected object frame
	MaxY float64 `json:"maxY,omitempty"`

	// the x coordinate of upper-left corner of detected object frame
	MinX float64 `json:"minX,omitempty"`

	// the y coordinate of upper-left corner of detected object frame
	MinY float64 `json:"minY,omitempty"`

	// the name of the detected object
	ObjectName string `json:"objectName,omitempty"`

	// the probablity of the detected object
	Probability float32 `json:"probability,omitempty"`
}

// Validate validates this tensor flow object
func (m *TensorFlowObject) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this tensor flow object based on context it is used
func (m *TensorFlowObject) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TensorFlowObject) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TensorFlowObject) UnmarshalBinary(b []byte) error {
	var res TensorFlowObject
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
